[package]
name = "ssi-pq-node"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "ssi_pq_node"
crate-type = ["cdylib"]

[dependencies]
ssi-pq-core = { path = "../ssi-pq-core", features = ["wallet"] }
napi.workspace = true
napi-derive.workspace = true
serde_json.workspace = true
chrono.workspace = true
hex.workspace = true

[build-dependencies]
napi-build.workspace = true
