/**
 * Estes testes validam a biblioteca WebAssembly contra vetores gerados
 * pela API Node.js atual. A intencao e reproduzir a superficie comum:
 * JSON canonico, profiles, schema, DID, credencial assinada e PDF SSI-PQ.
 *
 * Comando para rodar:
 *   npm run test:wasm
 */

const assert = require('node:assert/strict');
const test = require('node:test');

const nodeCore = require('../npm/ssi_pq_core.node');
const wasm = require('../packages/wasm-node/pkg/ssi_pq_wasm.js');

const createdAt = '2026-05-27T00:00:00Z';
const issuedAt = '2026-05-27T00:00:00Z';

function toJson(value) {
  return JSON.stringify(value);
}

function fromJson(text) {
  return JSON.parse(text);
}

function createIssuer() {
  return nodeCore.createDid({
    mldsa: 'ML-DSA-65',
    mlkem: 'ML-KEM-768',
    createdAt
  });
}

function createSignedCredential(credentialId = 'cred_wasm_interop_test') {
  const issuer = createIssuer();
  const attributes = {
    titular: {
      nome: 'Ana Silva',
      documento: '123.456.789-00'
    },
    curso: 'Criptografia Pos-Quantica',
    nivel: 'Avancado'
  };
  const schema = nodeCore.createSchemaFromAttributes(attributes, {
    version: '1',
    createdAt
  });
  const signedCredential = nodeCore.issueCredentialFromSchema(
    schema,
    attributes,
    issuer.didDocument,
    issuer.privateKeys.mldsaPrivateKey,
    {
      credentialId,
      issuedAt,
      visiblePaths: ['titular.nome', 'curso', 'nivel']
    }
  );

  return { issuer, attributes, schema, signedCredential };
}

test('WASM foundation mirrors supported profiles and canonical JSON behavior', () => {
  assert.deepEqual(wasm.supportedProfiles(), [
    'ML-DSA-44',
    'ML-DSA-65',
    'ML-DSA-87',
    'ML-KEM-512',
    'ML-KEM-768',
    'ML-KEM-1024'
  ]);

  assert.equal(
    wasm.canonicalJson('{"z":1,"a":{"b":2,"a":1}}'),
    '{"a":{"a":1,"b":2},"z":1}'
  );
  assert.equal(wasm.canonicalJson('[{"b":2,"a":1},3]'), '[{"a":1,"b":2},3]');
  assert.throws(() => wasm.canonicalJson('{"a":'), /invalid JSON/);
  assert.throws(
    () => wasm.canonicalJson('{"a":1,"a":2}'),
    /duplicate JSON property name: a/
  );
});

test('WASM creates the same stable schema shape from JSON attributes', () => {
  const attributes = {
    nome: 'Ana',
    idade: 30,
    email: 'ana@example.com'
  };
  const options = { version: '1', createdAt };
  const schema = fromJson(
    wasm.createSchemaFromAttributesJson(toJson(attributes), toJson(options))
  );
  const nodeSchema = nodeCore.createSchemaFromAttributes(attributes, options);

  assert.equal(schema.type, 'ssi_schema_v1');
  assert.equal(schema.schema_id, nodeSchema.schema_id);
  assert.deepEqual(
    schema.attributes.map((attribute) => [attribute.path, attribute.type, attribute.required]),
    [
      ['subject.email', 'string', true],
      ['subject.idade', 'integer', true],
      ['subject.nome', 'string', true]
    ]
  );
});

test('WASM verifies DID document and signed credential generated by Node', () => {
  const { issuer, signedCredential } = createSignedCredential();

  assert.deepEqual(fromJson(wasm.verifyDidDocumentJson(toJson(issuer.didDocument))), {
    valid: true,
    fingerprintMatchesKeys: true
  });

  assert.deepEqual(
    fromJson(
      wasm.verifySignedCredentialJson(toJson(signedCredential), toJson(issuer.didDocument))
    ),
    { valid: true }
  );

  const changedCredential = structuredClone(signedCredential);
  changedCredential.credential.credential_id = 'cred_wasm_interop_changed';
  assert.deepEqual(
    fromJson(
      wasm.verifySignedCredentialJson(toJson(changedCredential), toJson(issuer.didDocument))
    ),
    { valid: false }
  );

  const otherIssuer = createIssuer();
  assert.deepEqual(
    fromJson(
      wasm.verifySignedCredentialJson(toJson(signedCredential), toJson(otherIssuer.didDocument))
    ),
    { valid: false }
  );
});

test('WASM extracts and verifies signed credential PDF generated by Node', () => {
  const { issuer, signedCredential } = createSignedCredential('cred_wasm_pdf_test');
  const pdfBase = Buffer.from(
    nodeCore.signedCredentialToPdf(signedCredential, {
      labels: {
        'titular.nome': 'Nome do titular',
        curso: 'Curso',
        nivel: 'Nivel'
      }
    })
  );
  const finalPdf = Buffer.from(
    nodeCore.embedSignedCredentialInPdf(
      pdfBase,
      signedCredential,
      issuer.didDocument,
      issuer.privateKeys.mldsaPrivateKey,
      { createdAt, didDocCid: 'bafy-wasm-did-doc' }
    )
  );

  assert.equal(finalPdf.subarray(0, 5).toString('latin1'), '%PDF-');

  const manifest = fromJson(
    wasm.extractCredentialManifestFromPdfBytes(new Uint8Array(finalPdf))
  );
  assert.equal(manifest.type, 'ssi_pdf_signature_v1');
  assert.equal(manifest.signed_credential.credential.credential_id, 'cred_wasm_pdf_test');

  const verification = fromJson(
    wasm.verifySignedCredentialPdfJson(new Uint8Array(finalPdf), toJson(issuer.didDocument))
  );
  assert.equal(verification.valid, true);
  assert.equal(verification.credential_signature_valid, true);
  assert.equal(verification.document_binding_signature_valid, true);
  assert.equal(verification.pdf_base_hash_valid, true);

  const tamperedPdf = new Uint8Array(finalPdf);
  tamperedPdf[100] ^= 0x01;
  const tamperedVerification = fromJson(
    wasm.verifySignedCredentialPdfJson(tamperedPdf, toJson(issuer.didDocument))
  );
  assert.equal(tamperedVerification.valid, false);
  assert.equal(tamperedVerification.errors.includes('PDF_BASE_HASH_MISMATCH'), true);
});
